Vagrant.configure("2") do |config|

  config.vm.define "web_app" do |web_app|
    web_app.vm.box = "bento/ubuntu-20.04-arm64"

    web_app.vm.network "private_network", ip: "192.168.33.10"

    web_app.vm.synced_folder "/Users/User/vagrantData", "/vagrant_data"

    web_app.vm.provider "parallels" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    web_app.vm.provision "shell", inline: <<-SHELL
      sudo apt update
      sudo apt install apache2 \
                      net-tools \
                      ghostscript \
                      libapache2-mod-php \
                      mysql-server \
                      php \
                      php-bcmath \
                      php-curl \
                      php-imagick \
                      php-intl \
                      php-json \
                      php-mbstring \
                      php-mysql \
                      php-xml \
                      php-zip -y

      sudo mkdir -p /srv/www
      sudo chown www-data: /srv/www
      curl https://wordpress.org/latest.tar.gz | sudo -u www-data tar zx -C /srv/www

      cp /vagrant/provisioning/wordpress.conf /etc/apache2/sites-available/wordpress.conf

      sudo a2ensite wordpress
      sudo a2enmod rewrite
      sudo a2dissite 000-default
      sudo service apache2 reload

      mysql -u root -e 'CREATE DATABASE wordpress;'
      mysql -u root -e 'CREATE USER wordpress@localhost IDENTIFIED BY "password123";'
      mysql -u root -e 'GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON wordpress.* TO wordpress@localhost;'
      mysql -u root -e 'FLUSH PRIVILEGES;'

      sudo -u www-data cp /srv/www/wordpress/wp-config-sample.php /srv/www/wordpress/wp-config.php
      sudo -u www-data sed -i 's/database_name_here/wordpress/' /srv/www/wordpress/wp-config.php
      sudo -u www-data sed -i 's/username_here/wordpress/' /srv/www/wordpress/wp-config.php
      sudo -u www-data sed -i 's/password_here/password123/' /srv/www/wordpress/wp-config.php
      service mysql restart
    SHELL
  end

  config.vm.define "server_app" do |server_app|
    server_app.vm.box = "bento/ubuntu-20.04-arm64"

    server_app.vm.network "private_network", ip: "192.168.33.11"

    server_app.vm.synced_folder "/Users/User/vagrantData", "/vagrant_data"

    server_app.vm.provider "parallels" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    server_app.vm.provision "shell", inline: <<-SHELL
      sudo apt update
      sudo apt install net-tools \
                      mysql-server \ -y

      mysql -u root -e 'CREATE DATABASE randomdbname;'
      mysql -u root -e 'CREATE USER randomuser@localhost IDENTIFIED BY "password123";'
      mysql -u root -e 'FLUSH PRIVILEGES;'

      service mysql restart
    SHELL
  end
end
