Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04-arm64"
  config.vm.network "private_network", ip: "192.168.33.10"

  config.dns.tld = "test"
  config.vm.hostname = "machine"
  config.dns.patterns = [/^(\w+\.)*gitlab\.test$/]

  config.vm.provider "parallels" do |vb|
    vb.memory = "3000"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y curl \
                            openssh-server \
                            ca-certificates \
                            tzdata \
                            perl
    
    curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash
    
    sudo EXTERNAL_URL="https://gitlab.test" apt-get install gitlab-ce -y
  SHELL
end
