Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04-arm64"
  config.vm.network "private_network", ip: "192.168.33.10"

  config.dns.tld = "test"
  config.vm.hostname = "machine"
  config.dns.patterns = [/^(\w+\.)*gitlab\.test$/]

  config.vm.provider "parallels" do |vb|
    vb.memory = "3000"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y curl \
                            openssh-server \
                            ca-certificates \
                            tzdata \
                            perl \
                            gnupg

    # Docker
    sudo mkdir -m 0755 -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    sudo chmod a+r /etc/apt/keyrings/docker.gpg

    echo \
    "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    sudo apt-get update
    sudo apt-get install -y docker-ce \
                        docker-ce-cli \
                        containerd.io \
                        docker-buildx-plugin \
                        docker-compose-plugin

    # GitLab
    curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash
    sudo EXTERNAL_URL="https://gitlab.test" apt-get install -y gitlab-ce
    sudo docker --version

    # Docker gitlab-runner
    docker run -d --name gitlab-runner --restart always \
              -v /srv/gitlab-runner/config:/etc/gitlab-runner \
              -v /var/run/docker.sock:/var/run/docker.sock \
              gitlab/gitlab-runner:latest
  SHELL
end
